# "Data is Dirty
## I Repeat data is dirty"




![](https://th.bing.com/th/id/OIP.ETmCZRVzJ5xNc3f8REj9KQHaFt?pid=ImgDet&rs=1)

Data preprocessing is a major part of any machine learning process. As we know the major part of any machine learning model is for sure data and if the data is not in proper shape and form, the model will not perform at its best. So we have to make sure we process the data in right form so that future work on the data becomes meaningful.

The major steps in Data Preprocessing are: 
1. Data Collection
2. Importing Libraries
3. Dealing with Missing data
4. Data Reduction
5. Feature Importance / Feature Selection
6. Standardization
7. PCA
8. Train_test


# 1. Data Collection
Data is everything, without data there is no machine learning models. So the first step is always data collection. We have to collect data from various resources. sometimes in real life scenario we need to scrap data from various resources as formatted data is not available. for that various libraries and extension are available. However here, we are mainly focused in collecting data from various datasets centres, websites that have achieves of various data. We can collect data from [www.kaggle.com](https://www.kaggle.com) or [https://archive.ics.uci.edu/ml/machine-learning-databases](https://archive.ics.uci.edu/ml/machine-learning-databases) .

Other to it, you can do data scraping using various libraries or tools to get data but as of now, YO 2Ta WEBSITES WILL BE ENOUGH. 


# 2. Importing Libraries
we have to import all the important libraries that will be used for all the preprocessing. The basis python libraries are: NumPy, Pandas, Matplotlib, seaborn, sKlearn........

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Dealing with missing data

1. Data missed at Random
    
    During survey or at the time of data collection, the participants might missed filling up certain data, this can be a reason data are missing.
    
2. Data missed at Reason
    
    There can the scenario where the participants intentionally doesnt want to provide certain data like the phone number or the address for personal reasons. This can be the reason, the dataset can have multiple Null values.

So, if we came across missing data, we have to follow following types of ideas to deal with missing data. 

First we have to check the number of missing data in a column. If the percentage of missing data is more than 60% of the total data points, then there is no reason we have to keep that data column as it will have negative response to our future Machine Learning model. So, its always better to drop these columns. 

Second, we can also drop rows if the number of Null values of a certain column is very less, as it will have no impact over large dataset. 

What we can also do is use statistical method to figure out what to replace with the missing data. 

In case of numerical data, we can go with Mean of the entire column and then replace with mean to the Null values.
In case of categorical data, we can use mode to replace the missing values. 

The ideas how to generate mean can slightly be different accoring to the kind of dataset we are working on. If one column is highly co-related with another column, what we can do is find mean as per the another column and replace as per it. 

Let's take an example for it, like we have two column, GDP and Country. So replacing mean of entire GDP column will not be a good idea as there will be GDP for both Rich and Poor Countries and sometimes, the missing values can be of Poor country, so mean will still be very high GDP for that country. 

Instead what we can do is, aggregate all the mean of particular country and find mean of that country only and replace it with that mean.

![Picture title](image-20220121-122633.png)

In [2]:
import numpy as np
from io import StringIO

In [3]:
csv_data = \
            '''
            A,B,C,D
            1.0, 2.0, 3.0, 4.0
            5.0, 6.0,,8.0
            10.0,11.0,12.0
            '''

In [4]:
import pandas as pd

In [5]:
df =pd.read_csv(StringIO(csv_data))
df_large = pd.read_csv('dataset_titanic.csv')

In [6]:
df

A     B     C    D
0            1.0   2.0   3.0  4.0
1            5.0   6.0   NaN  8.0
2           10.0  11.0  12.0  NaN

In [7]:
# df_large.describe()

In [8]:
# df_large.head()

In [9]:
# Number of missing values in each feature column
df.isnull().sum()

            A    0
B                0
C                1
D                1
dtype: int64

In [10]:
# df_large.isnull().sum()

In [11]:
df.values
# print(type(df.values))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

###### One of the most simplest echnique is to remove the orw or colum with tha tcontaisn missing data

In [12]:
# drop rows
df.dropna(axis=0)

A    B    C    D
0            1.0  2.0  3.0  4.0

In [13]:
# drop columns
df.dropna(axis=1)

A     B
0            1.0   2.0
1            5.0   6.0
2           10.0  11.0

dropna , method has other several parameters, such as ,
 1. only drop rows where all columsna re NAN

In [14]:
df.dropna(how='all') # no colum has alll NAN values

A     B     C    D
0            1.0   2.0   3.0  4.0
1            5.0   6.0   NaN  8.0
2           10.0  11.0  12.0  NaN

In [15]:
# drop rows that has less tha 4 real values

df.dropna(thresh=4) # row 1 and 2 has only 3 real values, so dropped

A    B    C    D
0            1.0  2.0  3.0  4.0

In [16]:
# onlt drop rows where NAN apperas in the spicific Column

df.dropna(subset=['C']) # NAN appears in 1 row in C column


A     B     C    D
0            1.0   2.0   3.0  4.0
2           10.0  11.0  12.0  NaN

#### Imputing Missing values

In [17]:
df['C']

0     3.0
1     NaN
2    12.0
Name: C, dtype: float64

In [18]:
mean = df['C'].mean()
mean
df['C'].fillna(mean)

0     3.0
1     7.5
2    12.0
Name: C, dtype: float64

In [19]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [20]:
imr = SimpleImputer(missing_values= np.NaN, strategy='mean')

In [21]:
imr = imr.fit(df.values)
imr.fit_transform(df.values)

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [22]:
imputed_data = imr.transform(df.values)

In [23]:
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

#### Scikit Learn Estimator API

fit - learn the parameter from training data 

transform - uses those learned paramters to trasform the data.

## Handling Categorical Data

###### Nominal and Ordinal features 
 1. Ordinal - thoese featurs that can be sored e.g. T shirt Size XL > L > M > S
 2. Nominal - that cannot be sorted e.g. T shirt Color , red, greeen,

A+,| A ra | B
3  | 2   | 1  

In [24]:
import pandas as pd

In [25]:
df= pd.DataFrame([
    ['greeen', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1']
])

df.columns = ['color', 'size','price', 'classlabel']


In [26]:
df

color size  price classlabel
0  greeen    M   10.1     class1
1     red    L   13.5     class2
2    blue   XL   15.3     class1

###### Mapping Ordinal Features

e.g 
XL = L +1 = M+2

In [27]:
size_mapping = {
    'XL':3,
    'L':2,
    'M':1
}

In [28]:
df['size'] = df['size'].map(size_mapping)

In [29]:
df

color  size  price classlabel
0  greeen     1   10.1     class1
1     red     2   13.5     class2
2    blue     3   15.3     class1

#### Encoding the Class labels

In [30]:
import numpy as np

In [31]:
df

color  size  price classlabel
0  greeen     1   10.1     class1
1     red     2   13.5     class2
2    blue     3   15.3     class1

In [32]:
class_mapping = {label:idx for idx, label in enumerate(np.unique(df['classlabel']))}


In [33]:
df['classlabel'].unique() 

array(['class1', 'class2'], dtype=object)

In [34]:
class_mapping

{'class1': 0, 'class2': 1}

In [35]:
df['classlabel'] =df['classlabel'].map(class_mapping)

In [36]:
df

color  size  price  classlabel
0  greeen     1   10.1           0
1     red     2   13.5           1
2    blue     3   15.3           0

Scikit learn Label Encoder can also be used here

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
class_le = LabelEncoder()


In [39]:
y = class_le.fit_transform(df['classlabel'].values)

In [40]:
X = df.values
X

array([['greeen', 1, 10.1, 0],
       ['red', 2, 13.5, 1],
       ['blue', 3, 15.3, 0]], dtype=object)

#### Performing one Hot Encoding in Nominal Feaures

In [41]:
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

In [42]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'),[0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)


In [43]:
X = ct.fit_transform(X)

In [44]:
X

array([[0.0, 1.0, 0.0, 1, 10.1, 0],
       [0.0, 0.0, 1.0, 2, 13.5, 1],
       [1.0, 0.0, 0.0, 3, 15.3, 0]], dtype=object)

green -> (0 1 0)

red -> (0 0 1)

blue -> (1 0 0)

In [45]:
# can also use pandas get_dummies

In [46]:
pd.get_dummies(df[['price', 'color', 'size']])


price  size  color_blue  color_greeen  color_red
0   10.1     1           0             1          0
1   13.5     2           0             0          1
2   15.3     3           1             0          0

## Partitioning data in train - test
training set ko data

validation set ko data

testing set ko data 

 Train Test Split
 
The train_test_split function is for splitting a single dataset for two different purposes: training and testing. The testing subset is for building your model. The testing subset is for using the model on unknown data to evaluate the performance of the model

Train Dataset: Used to fit the machine learning model.

Test Dataset: Used to evaluate the fit machine learning model.

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [48]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/''ml/machine-learning-databases/''wine/wine.data', header=None)

In [49]:
df_wine.columns =['Class label', 'Alcohol', 'Malic acid', 'Ash',
                 'Alcalinity of ash',
                  'Magnesium',
                  'Total phenols', 'Flavanoids',
                  'Nonflavanoid phenols',
                  'Proanthocyanins',
                  'Color intensity', 'Hue',
                  'OD280/OD315 of diluted wines',
                  'Proline'
                 ]

In [50]:
df_wine

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0              1    14.23        1.71  2.43               15.6        127   
1              1    13.20        1.78  2.14               11.2        100   
2              1    13.16        2.36  2.67               18.6        101   
3              1    14.37        1.95  2.50               16.8        113   
4              1    13.24        2.59  2.87               21.0        118   
..           ...      ...         ...   ...                ...        ...   
173            3    13.71        5.65  2.45               20.5         95   
174            3    13.40        3.91  2.48               23.0        102   
175            3    13.27        4.28  2.26               20.0        120   
176            3    13.17        2.59  2.37               20.0        120   
177            3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [51]:
np.unique(df_wine['Class label'])

array([1, 2, 3])

In [52]:
from sklearn.model_selection import train_test_split


In [53]:
X ,y = df_wine.iloc[:,1:].values, df_wine.iloc[:, 0].values


In [54]:
X_train,X_test, y_train, y_test = train_test_split(X, y , test_size =0.3, random_state =42, stratify =y)

In [55]:
X_test

array([[1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.217e+01, 1.450e+00, 2.530e+00, 1.900e+01, 1.040e+02, 1.890e+00,
        1.750e+00, 4.500e-01, 1.030e+00, 2.950e+00, 1.450e+00, 2.230e+00,
        3.550e+02],
       [1.419e+01, 1.590e+00, 2.480e+00, 1.650e+01, 1.080e+02, 3.300e+00,
        3.930e+00, 3.200e-01, 1.860e+00, 8.700e+00, 1.230e+00, 2.820e+00,
        1.680e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.307e+01, 1.500e+00, 2.100e+00, 1.550e+01, 9.800e+01, 2.400e+00,
        2.640e+00, 2.800e-01, 1.370e+00, 3.700e+00, 1.180e+00, 2.690e+00,
        1.020e+03],
       [1.372e+01, 1.430e+00, 2.500e+00, 1.670e+01, 1.080e+02, 3.400e+00,
        3.670e+00, 1.900e-01, 2.040e+00, 6.800e+00, 8.900e-01, 2.870e+00,
        1.28

### Bringing Features into the same scales

#### Normaizlation - in range of (0, 1)

![Picture title](image-20220121-162604.png)

![Picture title](image-20220121-162638.png)

In [56]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()



In [57]:
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

#### Standarization - mean -0 ,  Var -1

![Picture title](image-20220121-162517.png)


In [58]:
from sklearn.preprocessing import StandardScaler


In [59]:
stdsc = StandardScaler()

In [60]:
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=57949008-d14a-4ee2-8f47-e94cc0939f85' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>