**1**
* Perform normal equation for the given linear regression problem


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#generating some linear looking data 
np.random.seed(0)
x  = 4 * np.random.rand(100,1)
y = -2 + 6 * x + np.random.rand(100,1)

#code starts here

#code ends here

**2**

* Perform linear regression, polynomial regression(degree = 3,4 and 5) and visualize them for the given dataset

* Plot learning curves for degree 3 polynomial regression and linear regression.

* Also apply decision tree as well



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Importing the dataset
dataset = pd.read_csv('https://s3.us-west-2.amazonaws.com/public.gamelab.fun/dataset/position_salaries.csv')

X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 2].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#your answer starts here

#your answer ends here
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [ ]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
X_test

array([[3],
       [9]])

In [ ]:
y_train

array([ 110000, 1000000,   50000,  200000,  300000,   80000,   45000,
        150000])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=57949008-d14a-4ee2-8f47-e94cc0939f85' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>